### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by chan1108** [XHXIAIEIN/Auto-Download-QQMail-Attach#2]
![image](https://user-images.githubusercontent.com/54262303/103119373-06f67100-46ae-11eb-923d-8b4662c4b040.png)

**Comment by XHXIAIEIN** [comment]
这里脚本是在检查邮箱左侧面板的 **标签** ，用于标记没有附件、过期附件的邮件。  
截图里抛出的异常是 ` TimeoutException ` ，页面找不到元素。  
我重新检查了一下，如果邮箱从来没有创建过标签的话，左侧是没有这个面板的。
  

临时解决方案：   
禁用脚本的标签功能，找到这两个属性，改成  0
```
can_tag_nofile = 0
can_tag_timeoutfile = 0
```

我会重新设计这一部分的代码，比如从邮箱设置里面添加标签，下个版本会解决。
感谢反馈！
