### ISSUE TITLE
浏览器版本过高无法支持

### ISSUE THREAD

**Issue by XLOIEUD** [XHXIAIEIN/Auto-Download-QQMail-Attach#5]
## 问题描述

**运行到哪一步报错： **

- [x]  无法运行脚本，点开就闪退
- [ ]  空白页面
- [ ]  邮箱主页
- [ ]  邮件列表
- [ ]  邮件正文
- [ ]  错误提示（例如502, 404, 你的请求过快，请稍后再试.....）

## 报错信息 

<details><summary>控制台信息</summary>

粘贴到这里

</details>

## 情况排查

- [ ] 1. 运行脚本，会自动开启一个浏览器。
- [ ] 2. 它有打开QQ邮箱页面，并自动**登录账号**。
- [ ] 3. 它有进入QQ邮箱主页，并自动跳转至**文件夹**。
- [ ] 4. 在文件夹页面，它会**自动翻页**，并自动收集**邮件标题**信息。
- [ ] 5. 它开始阅读邮件正文，并有自动收集**附件**信息。
- [ ] 6. 它开始下载附件，并成功**下载到指定的文件夹**位置。

**Comment by XLOIEUD** [comment]
“无法打开浏览器。检查是否已运行了另一个脚本。


Message: session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is 94.0.4606.81 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe”

**Comment by XHXIAIEIN** [comment]
可以手动更新一下 ChromeDriver (https://chromedriver.chromium.org/downloads) ，下载你当前 Chrome 浏览器对应的版本号，然后加到 Path 里面。更详细的安装步骤可以参考 README.md 里面被折叠的 《WebDriver for Chrome》 说明。
