### ISSUE TITLE
邮箱调用以及页面元素改版导致无法使用

### ISSUE THREAD

**Issue by GiGaFotress** [XHXIAIEIN/Auto-Download-QQMail-Attach#7]
在旧的代码中调用的文件夹地址https://mail.qq.com/cgi-bin/mail_list?folderid=133&page=0&sid=&nocheckframe=true
实际上新的地址:https://mail.qq.com/cgi-bin/frame_html?t=frame_html&sid="一串ID"&url=/cgi-bin/mail_list?folderid=133%26page=0
以及就算在弹出的sellum中替换了地址,仍然会报错
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
应该是有元素修改了导致定位有问题,

**Comment by XHXIAIEIN** [comment]
下载新版试试
